CREATE TABLE queens_player_records
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_name  VARCHAR(100)                            NOT NULL,
    solution_key VARCHAR(100)                            NOT NULL,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_queens_player_records PRIMARY KEY (id)
);

CREATE TABLE queens_solutions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solution_key   VARCHAR(100)                            NOT NULL,
    solution_array VARCHAR(200)                            NOT NULL,
    is_claimed     BOOLEAN,
    claimed_by     VARCHAR(255),
    claimed_at     TIMESTAMP WITHOUT TIME ZONE,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_queens_solutions PRIMARY KEY (id)
);

CREATE TABLE queens_solver_runs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    solver_type       VARCHAR(255)                            NOT NULL,
    solutions_found   INTEGER                                 NOT NULL,
    execution_time_ms BIGINT                                  NOT NULL,
    ran_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_queens_solver_runs PRIMARY KEY (id)
);

ALTER TABLE queens_solutions
    ADD CONSTRAINT uc_queens_solutions_solution_key UNIQUE (solution_key);