spring.application.name=backend
server.port=8081

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?user=postgres.xfgqzjpkylcrrstqnrik&password=wccr0h3Fx4mbKeas
spring.datasource.username=postgres
spring.datasource.password=wccr0h3Fx
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# CORS
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173