spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:postgresql://db.xfgqzjpkylcrrstqnrik.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=wccr0h3Fx4mbKeas
spring.datasource.driver-class-name=org.postgresql.Driver

# During development/tests allow Hibernate to update schema to create the migration table if missing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
